# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: libcecl.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='libcecl.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rlibcecl.proto\"\x83\x02\n\x14LibceclExecutableRun\x12\x1b\n\x13ms_since_unix_epoch\x18\x01 \x02(\x03\x12\x12\n\nreturncode\x18\x02 \x02(\x05\x12\x10\n\x08\x63\x65\x63l_log\x18\x03 \x02(\t\x12\x0e\n\x06stdout\x18\x04 \x02(\t\x12\x0e\n\x06stderr\x18\x05 \x02(\t\x12\x32\n\x11kernel_invocation\x18\x06 \x03(\x0b\x32\x17.OpenClKernelInvocation\x12\x17\n\x0f\x65lapsed_time_ns\x18\x07 \x02(\x03\x12\x1d\n\x15opencl_program_source\x18\x08 \x03(\t\x12\x1c\n\x14opencl_build_options\x18\t \x03(\t\"\xa3\x01\n\x16OpenClKernelInvocation\x12\x13\n\x0bkernel_name\x18\x01 \x02(\t\x12\x13\n\x0bglobal_size\x18\x02 \x02(\x03\x12\x12\n\nlocal_size\x18\x03 \x02(\x03\x12\x19\n\x11transferred_bytes\x18\x04 \x02(\x03\x12\x18\n\x10transfer_time_ns\x18\x05 \x02(\x03\x12\x16\n\x0ekernel_time_ns\x18\x06 \x02(\x03\"\xcf\x01\n\x0cOpenClDevice\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x15\n\rplatform_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65vice_name\x18\x03 \x01(\t\x12\x16\n\x0e\x64river_version\x18\x04 \x01(\t\x12\x16\n\x0eopencl_version\x18\x05 \x01(\t\x12\x13\n\x0b\x64\x65vice_type\x18\x06 \x01(\t\x12\x13\n\x0bplatform_id\x18\n \x01(\x05\x12\x11\n\tdevice_id\x18\x0b \x01(\x05\x12\x18\n\nopencl_opt\x18\x0c \x01(\x08:\x04true'
)




_LIBCECLEXECUTABLERUN = _descriptor.Descriptor(
  name='LibceclExecutableRun',
  full_name='LibceclExecutableRun',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ms_since_unix_epoch', full_name='LibceclExecutableRun.ms_since_unix_epoch', index=0,
      number=1, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='returncode', full_name='LibceclExecutableRun.returncode', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='cecl_log', full_name='LibceclExecutableRun.cecl_log', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stdout', full_name='LibceclExecutableRun.stdout', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stderr', full_name='LibceclExecutableRun.stderr', index=4,
      number=5, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kernel_invocation', full_name='LibceclExecutableRun.kernel_invocation', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='elapsed_time_ns', full_name='LibceclExecutableRun.elapsed_time_ns', index=6,
      number=7, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opencl_program_source', full_name='LibceclExecutableRun.opencl_program_source', index=7,
      number=8, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opencl_build_options', full_name='LibceclExecutableRun.opencl_build_options', index=8,
      number=9, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=277,
)


_OPENCLKERNELINVOCATION = _descriptor.Descriptor(
  name='OpenClKernelInvocation',
  full_name='OpenClKernelInvocation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='kernel_name', full_name='OpenClKernelInvocation.kernel_name', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='global_size', full_name='OpenClKernelInvocation.global_size', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='local_size', full_name='OpenClKernelInvocation.local_size', index=2,
      number=3, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transferred_bytes', full_name='OpenClKernelInvocation.transferred_bytes', index=3,
      number=4, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='transfer_time_ns', full_name='OpenClKernelInvocation.transfer_time_ns', index=4,
      number=5, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kernel_time_ns', full_name='OpenClKernelInvocation.kernel_time_ns', index=5,
      number=6, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=280,
  serialized_end=443,
)


_OPENCLDEVICE = _descriptor.Descriptor(
  name='OpenClDevice',
  full_name='OpenClDevice',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='OpenClDevice.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='platform_name', full_name='OpenClDevice.platform_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_name', full_name='OpenClDevice.device_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='driver_version', full_name='OpenClDevice.driver_version', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opencl_version', full_name='OpenClDevice.opencl_version', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_type', full_name='OpenClDevice.device_type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='platform_id', full_name='OpenClDevice.platform_id', index=6,
      number=10, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='device_id', full_name='OpenClDevice.device_id', index=7,
      number=11, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='opencl_opt', full_name='OpenClDevice.opencl_opt', index=8,
      number=12, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=True,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=446,
  serialized_end=653,
)

_LIBCECLEXECUTABLERUN.fields_by_name['kernel_invocation'].message_type = _OPENCLKERNELINVOCATION
DESCRIPTOR.message_types_by_name['LibceclExecutableRun'] = _LIBCECLEXECUTABLERUN
DESCRIPTOR.message_types_by_name['OpenClKernelInvocation'] = _OPENCLKERNELINVOCATION
DESCRIPTOR.message_types_by_name['OpenClDevice'] = _OPENCLDEVICE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LibceclExecutableRun = _reflection.GeneratedProtocolMessageType('LibceclExecutableRun', (_message.Message,), {
  'DESCRIPTOR' : _LIBCECLEXECUTABLERUN,
  '__module__' : 'libcecl_pb2'
  # @@protoc_insertion_point(class_scope:LibceclExecutableRun)
  })
_sym_db.RegisterMessage(LibceclExecutableRun)

OpenClKernelInvocation = _reflection.GeneratedProtocolMessageType('OpenClKernelInvocation', (_message.Message,), {
  'DESCRIPTOR' : _OPENCLKERNELINVOCATION,
  '__module__' : 'libcecl_pb2'
  # @@protoc_insertion_point(class_scope:OpenClKernelInvocation)
  })
_sym_db.RegisterMessage(OpenClKernelInvocation)

OpenClDevice = _reflection.GeneratedProtocolMessageType('OpenClDevice', (_message.Message,), {
  'DESCRIPTOR' : _OPENCLDEVICE,
  '__module__' : 'libcecl_pb2'
  # @@protoc_insertion_point(class_scope:OpenClDevice)
  })
_sym_db.RegisterMessage(OpenClDevice)


# @@protoc_insertion_point(module_scope)
